version: '3.4'
services:
  db:
    container_name: db
    image: library/mysql:5.6.22
    restart: always
    ports:
      - 8080:80
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_development
      - MYSQL_USER=
      - MYSQL_PASSWORD=
  
  app:
    container_name: app
    build: .
    volumes:
      - bundle:/usr/local/bundle
      - ".:/app"
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
    command: rails db:create && rails db:migrate && rails s -b 0.0.0.0

volumes:
  bundle:
    name: bundle

